export const projectsAbout = [{
    project_name: 'MyShop Ecommerce',
    project_symbol: 'Ms',
    project_year: 2021,
    project_description: 'Project developed as a part of Dare IT Mentorship programme for women. ',
    project_type: 'programming',
    project_stack: ['React', 'styled-components', 'postgreSQL', 'Mui-Library', 'React-Router', 'Node', 'Express'],
    project_category: 'Programming',
    project_status: 'WIP',
    project_link: 'https://github.com/mahtyns/mahtyns.github.io'
},
{
    project_name: 'Pam App Challenge',
    project_symbol: 'Pa',
    project_year: 2021,
    project_description: 'Presented for Reply Design Challenge 2021, in collaboration with my friend, Edyta Przybysz. The objective was to propose UX improvements for the famous Fitness App run by Pam. Our idea was to create a bigger sense of community, increase the engagement and keep all the fitness information the user might need in one place. We have added some new functionalities and shifted the focus to the app user.',
    project_type: 'designUI',
    project_stack: ['Figma', 'Photoshop', 'Illustrator'],
    project_category: 'Design',
    project_status: 'Finished',
    project_link: 'https://www.figma.com/file/6os6AexKkKm7BGhpOW7iWR/Pam-App-challenge', 
    project_imagesrc: 'https://i.ibb.co/cb1c5Rh/pamapp.gif', 
},
{
    project_name: 'WineLovers Store',
    project_symbol: 'Wi',
    project_year: 2020,
    project_description: 'Project for Domestika Course for HTML5, CSS3 and responsive web basics. ',
    project_type: 'designCode',
    project_stack: ['HTML', 'CSS'],
    project_category: 'Code',
    project_status: 'Finished',
    project_link: 'https://mahtyns.github.io/WineloversShop/',
    project_imagesrc: 'https://i.ibb.co/qdyxcZz/winelovers-shop-page.gif'

},
{
    project_name: 'Hangman Game',
    project_symbol: 'Ha',
    project_year: 2020,
    project_description: 'JavaScript project to practice new concepts.',
    project_type: 'programming',
    project_stack: ['Javascript'],
    project_category: 'Programming',
    project_status: 'WIP',
    project_link: 'https://mahtyns.github.io/hangmanGame/',
    project_imagesrc: 'https://i.ibb.co/d7fnSzR/hangmangame.gif'
},
{
    project_name: 'Sarai Web Redesign',
    project_symbol: 'Sr',
    project_year: 2021,
    project_description: 'Webpage redesign ',
    project_type: 'designUI',
    project_stack: ['Figma', 'Photoshop', 'Illustrator'],
    project_category: 'Design',
    project_status: 'Finished',
    project_link: 'https://www.behance.net/gallery/129222825/Sarais-web-page-refresh', 
    project_imagesrc: 'https://i.ibb.co/NxwzzBn/sarais.gif', 
},
{
    project_name: 'Friends after 30 Game',
    project_symbol: 'Fa',
    project_year: 2022,
    project_description: 'A React Native app with a party game',
    project_type: 'programming',
    project_stack: ['React Native'],
    project_category: 'Programming',
    project_status: 'WIP'
}]

